#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

cd $OPENSHIFT_DIY_DIR

rm -rf ${OPENSHIFT_DIY_DIR}jdk1.8.0_144
JAVA_JDK_URL="http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz"
JENKINS_URL="http://mirrors.jenkins.io/war/latest/jenkins.war"

wget --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" $JAVA_JDK_URL
tar -zxf ${OPENSHIFT_DIY_DIR}jdk-8u144-linux-x64.tar.gz
rm -f ${OPENSHIFT_DIY_DIR}jdk-8u144-linux-x64.tar.gz

rm -f jenkins.war
wget $JENKINS_URL
