#!/bin/bash

export JAVA_HOME=${OPENSHIFT_DIY_DIR}jdk1.8.0_144
export PATH=${JAVA_HOME}/bin:$PATH
export JENKINS_HOME=${OPENSHIFT_DATA_DIR}.jenkins

if [[ -z "$OPENSHIFT_INTERNAL_IP" ]]; then export OPENSHIFT_INTERNAL_IP="$OPENSHIFT_DIY_IP"; fi
if [[ -z "$OPENSHIFT_INTERNAL_PORT" ]]; then export OPENSHIFT_INTERNAL_PORT="$OPENSHIFT_DIY_PORT"; fi

nohup java -jar jenkins.war --httpListenAddress=$OPENSHIFT_DIY_IP --httpPort=$OPENSHIFT_DIY_PORT > ${OPENSHIFT_DATA_DIR}jenkins.log 2>&1 &
